spring:

  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/newdatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
   # url: jdbc:mysql://106.52.247.226:3306/newdatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

    username: root
    password: root  #本地数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
   # password: jmltzfbfqz     #服务器数据库密码


#  datasource:  #Oracle
#    url: jdbc:oracle:thin:@10.116.206.33:1521:jfora10
#    username: training
#    password: jf2019
#    driver-class-name: oracle.jdbc.driver.OracleDriver

#mybatis配置
mybatis:
  typeAliasesPackage: com.jmlt.kaifa.entity
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:config/mybatis-config.xml




server:
  port: 8080
